const GUI_CONFIG = {
  BAR_TOP_FROM_VIEWPORT_CENTER: "35vh",
  CARDBOARD_PANEL_CENTER_FROM_VIEWPORT_CENTER: "-25vh",

  BAR_WIDTH: "70vw",
  BAR_HEIGHT: "3px",
  BAR_COLOR: "black",

  OUT_OF_LINE_RESPONSE_PANELS_WIDTH: "12vw",
  OUT_OF_LINE_RESPONSE_PANELS_HEIGHT: "3.5vw",
  OUT_OF_LINE_RESPONSE_PANELS_ARROW_HEAD_WIDTH: "2vw",
  OUT_OF_LINE_RESPONSE_PANELS_ARROW_BODY_HEIGHT: "2.5vw",
  OUT_OF_LINE_RESPONSE_PANELS_COLOR: "lightgray",
  OUT_OF_LINE_RESPONSE_PANELS_HORIZONTAL_OFFSET_FROM_LINE: "0px",

  // TECHNICAL DETAILS
  BACKGROUND_COLOR: "white", //"blueviolet"
  CARDBOARD_BACKGROUND_COLOR: "wheat",//"yellow"
  CARDBOARD_FROZEN_BACKGROUND_COLOR: "#EE9A4D",
  CARDBOARD_HANDLE_DOT_COLOR: "black",

  LINE_FEEDBACK_COLOUR: "lightgreen",
  CARDBOARD_CORRECT_FEEDBACK_COLOUR: "green",
  CARDBOARD_INCORRECT_FEEDBACK_COLOUR: "red",

  POPUP_BUTTON_HEIGHT: "20px",
  POPUP_BUTTON_WIDTH: "20px",

  CARDBOARD_PANEL_SIZE: "150px",
  CARDBOARD_HANDLE_WIDTH: "6px",
  CARDBOARD_HANDLE_LENGTH: "115px",
  CARDBOARD_HANDLE_END_RADIUS: "20px",
  CARDBOARD_HANDLE_DOT_RADIUS: "4px",

  MAJOR_TICKS_HEIGHT: "2.4vw",
  MAJOR_TICKS_WIDTH: "6px",
  INTERMEDIATE_TICKS_HEIGHT: "2vw",
  INTERMEDIATE_TICKS_WIDTH: "5px",
  MINOR_TICKS_HEIGHT: "1.2vw",
  MINOR_TICKS_WIDTH: "4px",

  RESPONSE_MARGIN: "6px",

  UNIT_BACKGROUND_COLORS: ["none"],
  HEIGHT_BETWEEN_LABEL_AND_TICK: "1vh",
  LABEL_FONT_SIZE: 40,
}
// const GUI_CONFIG = {
//   BAR_TOP_FROM_VIEWPORT_CENTER: "400px",
//   CARDBOARD_PANEL_CENTER_FROM_VIEWPORT_CENTER: "-300px",
//
//   BAR_WIDTH: "1300px",
//   BAR_HEIGHT: "3px",
//   BAR_COLOR: "black",
//
//   OUT_OF_LINE_RESPONSE_PANELS_WIDTH: "200px",
//   OUT_OF_LINE_RESPONSE_PANELS_HEIGHT: "60px",
//   OUT_OF_LINE_RESPONSE_PANELS_ARROW_HEAD_WIDTH: "40px",
//   OUT_OF_LINE_RESPONSE_PANELS_ARROW_BODY_HEIGHT: "45px",
//   OUT_OF_LINE_RESPONSE_PANELS_COLOR: "lightgray",
//   OUT_OF_LINE_RESPONSE_PANELS_HORIZONTAL_OFFSET_FROM_LINE: "0px",
//
//   // TECHNICAL DETAILS
//   BACKGROUND_COLOR: "white", //"blueviolet"
//   CARDBOARD_BACKGROUND_COLOR: "wheat",//"yellow"
//   CARDBOARD_FROZEN_BACKGROUND_COLOR: "#EE9A4D",
//   CARDBOARD_HANDLE_DOT_COLOR: "black",
//
//   LINE_FEEDBACK_COLOUR: "lightgreen",
//   CARDBOARD_CORRECT_FEEDBACK_COLOUR: "green",
//   CARDBOARD_INCORRECT_FEEDBACK_COLOUR: "red",
//
//   POPUP_BUTTON_HEIGHT: "20px",
//   POPUP_BUTTON_WIDTH: "20px",
//
//   CARDBOARD_PANEL_SIZE: "150px",
//   CARDBOARD_HANDLE_WIDTH: "6px",
//   CARDBOARD_HANDLE_LENGTH: "115px",
//   CARDBOARD_HANDLE_END_RADIUS: "20px",
//   CARDBOARD_HANDLE_DOT_RADIUS: "4px",
//
//   MAJOR_TICKS_HEIGHT: "42px",
//   MAJOR_TICKS_WIDTH: "6px",
//   INTERMEDIATE_TICKS_HEIGHT: "34px",
//   INTERMEDIATE_TICKS_WIDTH: "5px",
//   MINOR_TICKS_HEIGHT: "20px",
//   MINOR_TICKS_WIDTH: "4px",
//
//   RESPONSE_MARGIN: "6px",
//
//   UNIT_BACKGROUND_COLORS: ["none"],
//   HEIGHT_BETWEEN_LABEL_AND_TICK: "20px",
//   LABEL_FONT_SIZE: 40,
// }
// const GUI_CONFIG = {
//   BAR_TOP_FROM_VIEWPORT_CENTER: "100mm",
//   CARDBOARD_PANEL_CENTER_FROM_VIEWPORT_CENTER: "-60mm",
//
//   BAR_WIDTH: "350mm",
//   BAR_HEIGHT: "1mm",
//   BAR_COLOR: "black",
//
//   OUT_OF_LINE_RESPONSE_PANELS_WIDTH: "48mm",
//   OUT_OF_LINE_RESPONSE_PANELS_HEIGHT: "16mm",
//   OUT_OF_LINE_RESPONSE_PANELS_ARROW_HEAD_WIDTH: "6mm",
//   OUT_OF_LINE_RESPONSE_PANELS_ARROW_BODY_HEIGHT: "11mm",
//   OUT_OF_LINE_RESPONSE_PANELS_COLOR: "lightgray",
//   OUT_OF_LINE_RESPONSE_PANELS_HORIZONTAL_OFFSET_FROM_LINE: "0mm",
//
//   // TECHNICAL DETAILS
//   BACKGROUND_COLOR: "white", //"blueviolet"
//   CARDBOARD_BACKGROUND_COLOR: "wheat",//"yellow"
//   CARDBOARD_FROZEN_BACKGROUND_COLOR: "#EE9A4D",
//   CARDBOARD_HANDLE_DOT_COLOR: "black",
//
//   LINE_FEEDBACK_COLOUR: "lightgreen",
//   CARDBOARD_CORRECT_FEEDBACK_COLOUR: "green",
//   CARDBOARD_INCORRECT_FEEDBACK_COLOUR: "red",
//
//   POPUP_BUTTON_HEIGHT: "5mm",
//   POPUP_BUTTON_WIDTH: "5mm",
//
//   CARDBOARD_PANEL_SIZE: "40mm",
//   CARDBOARD_HANDLE_WIDTH: "2mm",
//   CARDBOARD_HANDLE_LENGTH: "30mm",
//   CARDBOARD_HANDLE_END_RADIUS: "5mm",
//   CARDBOARD_HANDLE_DOT_RADIUS: "1mm",
//
//   MAJOR_TICKS_HEIGHT: "10mm",
//   MAJOR_TICKS_WIDTH: "2mm",
//   INTERMEDIATE_TICKS_HEIGHT: "8mm",
//   INTERMEDIATE_TICKS_WIDTH: "1.5mm",
//   MINOR_TICKS_HEIGHT: "5mm",
//   MINOR_TICKS_WIDTH: "1mm",
//
//   RESPONSE_MARGIN: "2mm",
//
//   UNIT_BACKGROUND_COLORS: ["none"],
//   HEIGHT_BETWEEN_LABEL_AND_TICK: "5mm",
//   LABEL_FONT_SIZE: 40,
// }
