// IMPORTANT STUFF
BAR_MIN = 0;
BAR_MAX = 7;//5;
MINOR_GRADUATION_VALUE = .1
INTERMEDIATE_GRADUATION_INTERVAL = .5
MAJOR_GRADUATION_INTERVAL = 1
TRIAL_TIME_LIMIT = 20000

USE_HALVES_TICKS = true;
USE_VERTICAL_SNAP = true;
USE_HORIZONTAL_SNAP = true;

FRACTION_IMAGE_PATH = "./res/fractions/"
FRACTION_AUDIO_PATH = "./res/fractions_audio/"
AUDIO_VOICES = ["CL"]//["man", "woman"]
IMAGE_ORIGINAL_DIMENSION = 150;

DOMAIN_TYPE = "BAR"
NUMBER_TYPE = "FRACTION"
FIRST_PART = 4
SECOND_PART = 10

NUMBER_OF_REPETITIONS = 2;

VISUAL_MODALITY = "visual"
VERBAL_MODALITY = "verbal"

SMALLER_PANEL_ID = "SMALLER"
GREATER_PANEL_ID = "GREATER"
TIME_BEFORE_FEEDBACK = 500
FEEDBACK_ANIMATION_DURATION = 800
AFTER_TRIAL_DELAY = 500;

LINE_PRIORITY = 0;
OUT_OF_LINE_RESPONSE_PANELS_PRIORITY = 1;

FEEDBACK_ERROR_THRESHOLD = 3;

const EPSILON = 0.0005
